import { Code2, ExternalLink, FileCode2, Globe2, Upload } from 'lucide-react';
import { QiyuAppShell } from '@/components/qiyu-app-shell';

export function SitesCenter() {
  return <QiyuAppShell active="sites" eyebrow="栖屿网页" title="网页发布">
    <div className="space-y-6"><section className="flex flex-col gap-4 border-b border-white/7 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-primary">静态网页空间</p><h2 className="mt-1.5 text-3xl font-medium tracking-[-0.045em]">把小网站放回自己手里。</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">上传 HTML、CSS 和资源文件，Caddy 会从同一入口发布它们。</p></div><a href="/files?path=sites" className="inline-flex h-8 w-fit items-center gap-1.5 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/85"><Upload className="size-4" />管理网页文件</a></section><section className="grid gap-3 md:grid-cols-3"><Step index="01" icon={FileCode2} title="建立目录" text="在 sites 下新建网站目录。" /><Step index="02" icon={Upload} title="上传文件" text="放入 index.html 和资源文件。" /><Step index="03" icon={Globe2} title="立即访问" text="访问 /sites/你的目录/。" /></section><section className="grid gap-4 lg:grid-cols-2"><a href="/sites/" className="group rounded-2xl border border-white/8 bg-white/[0.025] p-6 transition hover:border-primary/25 hover:bg-primary/[0.045]"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Globe2 className="size-5" /></div><h3 className="mt-6 text-lg font-medium">已发布网页</h3><p className="mt-2 text-sm text-muted-foreground">查看所有当前对内发布的静态站点和资源。</p><span className="mt-7 flex items-center gap-1 text-sm text-primary">打开目录 <ExternalLink className="size-3.5" /></span></a><div className="rounded-2xl border border-white/8 bg-[#101c1b] p-6"><div className="flex size-10 items-center justify-center rounded-xl bg-white/[0.05] text-primary"><Code2 className="size-5" /></div><h3 className="mt-6 text-lg font-medium">适合放什么？</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">个人介绍页、文档站、家庭相册索引和纯前端工具都很合适。需要动态后端的应用仍建议单独部署。</p></div></section></div>
  </QiyuAppShell>;
}

function Step({ index, icon: Icon, title, text }: { index: string; icon: typeof FileCode2; title: string; text: string }) { return <div className="rounded-xl border border-white/8 bg-white/[0.025] p-5"><span className="text-[11px] font-medium tracking-[0.16em] text-primary">{index}</span><Icon className="mt-6 size-5 text-foreground" /><h3 className="mt-4 text-sm font-medium">{title}</h3><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{text}</p></div>; }
